### ISSUE TITLE
[PATCH] FFI::Struct accessors

### ISSUE THREAD

**Issue by candlerb** [ffi/ffi#107]
The wiki suggests using swig or nice-ffi if you want accessor methods. But that seems like pulling in a lot of bloat for something that could be included easily:

```
class FFI::Struct
  def self.alayout(*fields)
    layout(*fields)
    fields.each_slice(2) do |name,type|
      define_method name do
        self[name]
      end
      define_method "#{name}=" do |v|
        self[name] = v
      end
    end
  end
end

# Demo
class Foo < FFI::Struct
  alayout :a, :int, :b, :int
end

f = Foo.new
f.a = 1
f.b = 2
p f.a
p f.b
```

**Comment by lwoggardner** [comment]
So 12 years later (this issue is referenced from the Wiki) and nice-ffi is untouched for 13 years.

I had a crack at this for ffi-libfuse - still in progress, but I think generally workable

Define accessor methods with #ffi_attr_reader ,#ffi_attr_writer, #ffi_attr_accessor - similar to native attr_reader etc, but some extra sugar to map attribute names to underlying struct member names, and provide blocks for data conversion.
https://github.com/lwoggardner/ffi-libfuse/blob/main/lib/ffi/accessors.rb

Solve the method conflict problems (like :size) with a StructWrapper  - essentially a data converter to FFI:Struct with minimal other methods defined. 
https://github.com/lwoggardner/ffi-libfuse/blob/main/lib/ffi/struct_wrapper.rb
