### ISSUE TITLE
Request for Platform-Specific Extensions for Ruby 3.4

### ISSUE THREAD

**Issue by tagliala** [ffi/ffi#1132]
Hello,

currently, platform-specific gems target `>= 2.5, < 3.4.dev`

Could platform-specific extensions be provided for Ruby 3.4?

**Comment by mockdeep** [comment]
Related, I am able to install the gem locally as it builds native extensions on demand, but then it [fails on Github Actions](https://github.com/mockdeep/subsequent/actions/runs/12529792651/job/34945732210?pr=75) due to the version requirements. Is there a way to configure it to build it on Actions?

**Comment by tagliala** [comment]
Since `Gemfile.lock` is checked in the repository, I was expecting to see also an update to Gemfile.lock in the PR

**Comment by mockdeep** [comment]
@tagliala the `Gemfile.lock` doesn't change for me when I run `bundle` on that branch.
