### ISSUE TITLE
read_array_of_* with 0 elements fails when memory is not accessible

### ISSUE THREAD

**Issue by jethrogb** [ffi/ffi#305]
```
[1] pry(main)> p
=> #<FFI::Pointer address=0x00000000000000>
[2] pry(main)> p.read_array_of_long(0)
FFI::NullPointerError: invalid memory read at address=0x00000000000000
from (pry):2:in `read_array_of_long'
```

I am expecting no memory reads when reading an array of length 0, so this should just return an empty array.

**Comment by headius** [comment]
Auditing old issues that mention me...

I'm not convinced that this shouldn't be an error condition, since any other value for the size would result in a segv.

Backing up the non-error point of view is this example using `memcpy`, which does not segv:

```c
#include <string.h>

int main(int argc, char** argv) {
  char* null = 0;
  char target[1];

  return (int) memcpy(target, null, 0);
}
```

This may run differently on other C libraries.

I don't care one way or another but this one is so trivial it would be nice to close it and get it out of the queue.

**Comment by larskanis** [comment]
Thanks @headius for telling your opinion! I think we shouldn't raise an error about an invalid memory access if there is no memory access. So #804 is my proposal to resolve this issue.
