### ISSUE TITLE
return type char * as :string ?

### ISSUE THREAD

**Issue by paddor** [ffi/ffi#467]
Sorry, but the docs really aren't clear on this.

Given the following C function prototype:

```c
char * somelib_encode (somelib_t *self, const byte *data, size_t data_size);
```

The return value is a pointer to a freshly allocated memory area. The caller is responsible for `free()`ing it later.

Is it safe to attach this function like this?

```ruby
attach_function :somelib_encode, [:pointer, :pointer, :size_t], :string
```

I know FFI will properly read the C string (the function guarantees that there's only one trailing NULL byte) and return it as a Ruby String object. But what happens to the memory area?

Does FFI have the possibility to examine the exact C function prototype to see if the return value is `const`, and, if not, should be `free()`d later?

Please document this clearly.

**Comment by larskanis** [comment]
You can use the `:strptr` return type. See our specs [here](https://github.com/ffi/ffi/blob/master/spec/ffi/strptr_spec.rb) . Or you might use a plain `:pointer` type.

BTW: Using stdlib's `free()` function to free memory returned from a library is a bad API design. It could be, that memory handling is different between the library context and the application context, so that library's `malloc()` and application's `free()` might use different implementations.

> Please document this clearly.

We always appreciate any help on documentation issues. Feel free to open a pull request or contribute to the project wiki.

**Comment by paddor** [comment]
Sorry, but that doesn't answer my question, nor do the specs. Will it `free()` the memory or not?

Thanks for the hint, and of course you're right. But in this case, it's a `calloc()`'d C string, that gets explicitly handed off by the library.

I will gladly update your wiki, but to be able to do that, I have to have confidence in how it works. What's the difference between the types `:string` and the type `:strptr`?

**Comment by larskanis** [comment]
You need to free the memory yourself. Something like this should work:
```ruby
  module Stdio
    extend FFI::Library
    ffi_lib FFI::Platform::LIBC
    attach_function :free, [ :pointer ], :void
  end

  module MyLib
    extend FFI::Library
    attach_function :somelib_encode, [:pointer, :pointer, :size_t], :pointer
  end

  p_input = FFI::MemoryPointer.from_string("input")
  p_out = MyLib.somelib_encode(this, p_input, p_input.size)
  p p_out.get_string(0)
  Stdio.free(p_out)
```

It's best to look into the ffi-sources if you're in doubt. Github search or `git grep` is great for this.

**Comment by paddor** [comment]
Thanks for answering the question.

Also, thanks for the example. It makes sense, but looks pretty messy. What about AutoPointer? I'm not sure, but it kinda sounds like the thing to use when I want automatic release of memory.

**Comment by larskanis** [comment]
Of course, you can use an AutoPointer-subclass and call `Stdio.free` in it's `release` method.

**Comment by paddor** [comment]
Thanks for the info. I did some code digging, improved documentation, and filed a [PR](https://github.com/ffi/ffi/pull/468).

I also improved the following wiki pages:

* https://github.com/ffi/ffi/wiki/Pointers (big section added)
* https://github.com/ffi/ffi/wiki/Home (link to pointers)
* https://github.com/ffi/ffi/wiki/Binary-data (more modern Ruby code, C example fixed)
* https://github.com/ffi/ffi/wiki/Types (tabelized, added `:strptr`)
* https://github.com/ffi/ffi/wiki/Examples (minor structure improvement)

**Please check** at least the [Fresh Memory](https://github.com/ffi/ffi/wiki/Pointers#fresh-memory) section on the Pointers page, as I'm not sure if it's correct. Haven't actually tried it yet. Does it look okay to you?

**Comment by paddor** [comment]
I checked the FFI documentations again and am totally confused now. It says that FFI::Pointer has an `autorelease` attribute and a `#free` method. If that attribute is set (which, by default, it is), will automatically release the associated memory when freed.

So what's AutoPointer for?

I see that the `#free` method (implemented in C) calls `xfree()`. But that function is nowhere declared, nor defined in the FFI sources.

Can `#free` be used to platform-independently free memory? (I guess your code example above isn't really platform-independent.)

**Comment by larskanis** [comment]
`FFI::Pointer#free` can be used to free memory, when it was allocated by ffi (with `FFI::MemoryPointer.new(:char)` or similar) . Otherwise the memory is free'd by the GC.

However `FFI::Pointer#free` is not usable to free externally allocated memory. This is consequent in that regard, that allocation and free should be done by the same library. There is no guarantee, that mix and match will work.

`xmalloc()` , `xfree()`  , `ALLOC()` etc. are ruby-internal memory management functions. They relay on stdlib functions, but are extended for ruby GC, exceptions handling and locking.

free() should work on most platforms, but you need to use a underscored function name on Windows:
```ruby
attach_function :_free, [ :pointer ], :void
```

**Comment by paddor** [comment]
>FFI::Pointer#free can be used to free memory, when it was allocated by ffi (with >FFI::MemoryPointer.new(:char) or similar) . Otherwise the memory is free'd by the GC.

What do you mean by "otherwise"? I doubt that Ruby's GC can native memory...

What if that library function internally does nothing else than `free()` in case there was an error? Would the `FFI::Pointer#free` work in that case? Or do I still have to attach libc's `free()`?

Thanks for the further info.

Did you see my documentation contributions?
