### ISSUE TITLE
Pointer to a function, unclear documentation

### ISSUE THREAD

**Issue by naddika** [ffi/ffi#832]
At https://github.com/ffi/ffi/wiki/Structs#pointers-to-functions it's unclear:

```
class FunctionTable < FFI::Struct
  layout :function1, callback([:pointer, :int], :void)  # A pointer to an anonymous function that takes a pointer and an integer

  # or more verbose with a named callback:
  layout :function1, :completion_function  # A pointer to the named callback function
end

callback :completion_function, [:pointer, :long, :uint8], :void  # define a named callback
attach_function :factory, [], :FunctionTable.by_ref

```

Are these 3 different pointers to 3 different functions? Or 1 pointer written in 3 different forms? Or 2 pointers? 

How to read it?

Does doing it via a struct required or optional? Can it be done without it?

What does a C pointer to a function look like for this?

**Comment by ParadoxV5** [comment]
> Are these 3 different pointers to 3 different functions? Or 1 pointer written in 3 different forms? Or 2 pointers?

1 pointer written in 2 different forms. I have updated the example.

> Does doing it via a struct required or optional? Can it be done without it?

In general, optional, `callback` is an `FFI::Library` module method, and the example only demonstrates using a function pointer as a `layout` type.
For the context of this example though, required, because the `factory` method expects a pointer to a `FunctionTable` which is a `Struct` whose sole member is a pointer to a function with the above signature.

> What does a C pointer to a function look like for this?

I’m a C newbie. Experts, correct me if I mistook something. (:

```c
typedef struct {
	void *(*function1)(void*, int);
} FunctionTable;
```

(Sorry for necroposting, I just wanna do some housekeeping – one issue closed is one less open issue, y’know.)

**Comment by larskanis** [comment]
@ParadoxV5 thank you for your contributions to ffi wiki and issues! They are very appreciated!
