### ISSUE TITLE
'Could not open library' dll in Windows

### ISSUE THREAD

**Issue by agonzalezesteve** [ffi/ffi#842]
I'm trying to use the gem in Windows in order to load a custom C library.

The "Hello, world!" in the README of the repository works but I don't know how to load C functions written by me.

I'm testing this simple C function
```
# sum.c
int sum(int a, int b) {
  return a + b;
}
```
and trying to use it in Ruby.
```
# sum.rb
require 'ffi'

module Sum
  extend FFI::Library
  ffi_lib 'sum'
  attach_function :sum, [ :int, :int ], :int
end

p Sum.sum(1, 2)
```

But I get the following error:
```
Traceback (most recent call last):
        4: from test_ffi.rb:4:in `<main>'
        3: from test_ffi.rb:6:in `<module:MyLib>'
        2: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.13.1-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
        1: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.13.1-x64-mingw32/lib/ffi/library.rb:99:in `map'
 (LoadError)4/lib/ruby/gems/2.6.0/gems/ffi-1.13.1-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib': Could not open library 'sum': The specified module could not be found.
.
Could not open library 'sum.dll': The specified module could not be found.
```

I've tried [this](https://stackoverflow.com/questions/54499254/how-do-i-identify-why-ruby-ffi-and-vb-net-cant-load-a-dll-file), [this](https://stackoverflow.com/questions/25470079/ruby-ffi-does-not-load-dll-on-windows), [this](https://www.ruby-forum.com/t/ffi-with-dlls-compiled-by-mingw/182664) and checked the issues, but nothing worked.

I've this version of Ruby:
```
ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
```
I'm using the version 1.31.1 of FFI.
I've used gcc complilers for 32 and 64 bits.
I'm using Windows 10 with 64 bits.

**Comment by larskanis** [comment]
Some thoughts:
1. Which compiler did you use? The gcc from RubyInstaller+Devkit should work flawlessly after running `ridk enable` in the console.
2. Did you try a absolute path to `ffi_lib` ? Otherwise you'll have to use `RubyInstaller::Runtime.add_dll_directory` to add a specific directory to the DLL load paths as described here: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#-dll-loading
3. If it still doesn't work, you can enable DLL loader debugging as described here: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#-debug-dll-loading

**Comment by agonzalezesteve** [comment]
Ok, it worked!

I did:
1. I "Start Command Prompt with Ruby", execute `ridk enable` in the console and I compiled the `.dll` with gcc from Ruby.
2. I used the absolute path in `ffi_lib`. 

I guees it's the first step because I [struugled](https://www.ruby-forum.com/t/ffi-with-dlls-compiled-by-mingw/182664) with the absolute path before.

**Comment by IgorJorobus** [comment]
Hi Lars. I know this is closed but wanted to ask, why do you think the gcc compiler that comes nowadays with the ruby installer works somehow (at least dll compiled with them can be imported with FFI) differently than the MinGW gcc compiler downloaded directly from their official website? Any clue?

**Comment by larskanis** [comment]
@IgorJorobus I asked for the compiler because different compiler can use different dependencies. These DLLs might not be satisfied, so that the primary DLL can not be loaded. Unfortunately the error message that Windows raises doesn't contain any details about the reason, why a DLL couldn't be loaded. Apart from this, ffi can load any DLLs that are built according to the Windows-ABI regardless by which compiler.

When loading a Windows DLL with RubyInstaller there's an additional thing to note. RubyInstaller enforces a clear separation between load paths of EXE files and DLL files as described in: https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#-dll-loading
