### ISSUE TITLE
Struct taking more bytes than it should and causing Segfault

### ISSUE THREAD

**Issue by IgorJorobus** [ffi/ffi#872]
Hi guys,

I require some help, if possible. I made my binding work, compiling and executing everything with x32. When I try the same with x64, Segfault gets raised. This is where it happens:

![image](https://user-images.githubusercontent.com/1852056/103575487-92db7a80-4eb0-11eb-9fed-87efa253c2b1.png)

Problem appears with `get_string(0)`. This is the definition of those structures. `@native_cell` is an instance of `XLSXCellT`:

![image](https://user-images.githubusercontent.com/1852056/103575746-efd73080-4eb0-11eb-943c-67b816d29414.png)

I've inspected the size of `@native_cell` when x32, it's 16 bytes (as expected); and the size when x64, it's 24 when it should be 20, since I've inspected the size of every type used and gives for x64:

* **pointer**: 8 bytes
* **int**: 4 bytes
* **union**: 8 bytes (since the largest member is `char *` or `double` or `long long` with 8 bytes) and it's in fact 8 (a call to `@native_cell[:valuje].size` gives 8).

If you sum up that, it gives 20 bytes, but the struct is measuring 24 bytes. Offsets are well set, 0, 8 and 12. I've inspected what's in those 4 last bytes and we have all 0's, not important I guess because could probably have anything. The problem is that when I access a member of the union, and try to read its data, by any method you could recall (I tested read_string(), get(), get_bytes(), read(), get_string(), etc.) a Segfault is raised:

![image](https://user-images.githubusercontent.com/1852056/103577239-2dd55400-4eb3-11eb-8f09-65604355e634.png)

The weirdest thing is when I try to measure the size of one of the members of the union (should get a maximum of 8 bytes):

![image](https://user-images.githubusercontent.com/1852056/103577164-0d0cfe80-4eb3-11eb-800a-74e9e1f7e272.png)

Am I missing something? I'll appreciate some guidance on the matter. Let me know how can I help further.

D.

**Comment by larskanis** [comment]
The size of the struct is always aligned to the size of the biggest member. The last 4 bytes are unused, if you manually set the offset like you did above. Otherwise the automatic placement inserts 4 unused bytes between `value_type` and `value`, like a C compiler would do.

If accessing a pointer segfaults or not depends entirely on the validity of the pointer. So you must make sure, that either your ruby code or the called C code sets the pointer properly before calling `read_string`, etc.

The size 2147483647 is the (dummy) size limit of an unlimited pointer.

You can check the struct content by something like this:
```ruby
s = XLSXCellT.new
s.pointer.read_bytes(s.size)
```

Could it be that you should use automatic struct layout to get the correct pointer?

**Comment by larskanis** [comment]
Side note: `x32` usually refers to the 32 bit ABI of x86_64 Linux. On Windows you should use `x86` instead. There is no x32-ABI on Windows.

**Comment by IgorJorobus** [comment]
Hi Lars,

Thank you very much for the quick answer. You were right, **manually setting the offsets was causing the problem**. I had the code that way since 2 years ago, I've retook the project now, can't recall why I was setting the offsets manually. Anyways, **it works now for x86 and x64**. Thanks again and have a good year.
