### ISSUE TITLE
Version conflicts between Rubies, FFI versions, and architectures -- advice requested

### ISSUE THREAD

**Issue by jordansissel** [ffi/ffi#906]
Hi!

I'm the maintainer of [fpm](https://github.com/jordansissel/fpm/) and this software uses ffi. I do my best to support a wide range of Ruby versions because, too often, folks don't have much direct control over which version of Ruby they have available.

I'm stuck on a problem with respect to compatibility between ruby versions, ffi versions, and some platforms.

Example: A user stuck on [Ruby 2.2 cannot use FFI 1.13](https://github.com/jordansissel/fpm/issues/1708).

To solve this, we [pinned to ffi 1.12.x](https://github.com/jordansissel/fpm/pull/1709). This solved one problem, but created a another, that ffi fails for folks on [Arch linux (only has ffi 1.15 available)](https://github.com/jordansissel/fpm/pull/1709#issuecomment-802358677) and [newer arm-based Macs (requires ffi 1.14)](https://github.com/jordansissel/fpm/pull/1709#issuecomment-770260038).

I don't think gemspec supports the complex matrix of mapping platform+ruby to runtime dependencies, so I'm not sure how to solve this.

Any advice you can provide on this scenario would be much appreciated :)

**Comment by larskanis** [comment]
A very valuable recommendation for versioning issues is http://semver.org . It doesn't directly answer your specific question, but acts as a base contract between arbitrary projects.

In general you shouldn't specify 3 digits versions like ~>1.12.0 but only ~>1.12 unless you've got a good reason to do so (like doing monkey patching of the library in question).

The other recommendation is to only specify the version requirements of _your_ gem in your gemspec. You shouldn't try to solve issues of other gems in your gemspec. It's the task of Rubygems and Bundler to resolve all requirements, so that they all fit together. So if your gem works with ffi-1.9 and newer, you should simply specify ~>1.9 and nothing else. Rubygems isn't particular clever, to solve Ruby version dependencies, but Bundler is usually and should pick the right ffi version for Ruby-2.2.

Pinning to a specific ffi minor version not only prevents new supported environments as you describe, but also blocks your gem to be used together with another gem, that requires a newer version of ffi.

**Comment by jordansissel** [comment]
Thanks for the quick response.
