### ISSUE TITLE
Addition to Closure API that allocate/prepare the closure in one call?

### ISSUE THREAD

**Issue by TerrorJack** [ffi/ffi#933]
We're porting `libffi` to `wasm32`, and due to certain constraints, the original Closure API can't be implemented per se, it can only work when the allocation/preparation of the closure is done in a single call, where the type information is available. Would `libffi` upstream be interested in accepting such a function, with the behavior for native archs described below?

```c
ffi_status ffi_alloc_prep_closure(ffi_closure **pclosure, ffi_cif *cif,
                                  void (*fun)(ffi_cif *cif, void *ret,
                                              void **args, void *user_data),
                                  void *user_data, void **code) {
  *pclosure = ffi_closure_alloc(sizeof(ffi_closure), code);
  return ffi_prep_closure_loc(*pclosure, cif, fun, user_data, *code);
}
```

**Comment by larskanis** [comment]
This project is about ruby-ffi. You maybe want to post your change request in https://github.com/libffi/libffi .

Regarding ruby-ffi, I'm open to add such a new function. Although we have some [custom trampoline code](https://github.com/ffi/ffi/blob/2cc0e530710501e3ef1bfebaa2122e45b439476a/ext/ffi_c/MethodHandle.c#L199-L211), which is used instead of `ffi_prep_closure_loc`, but it's probably not usable in a wasm context anyway.
